apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: apps
  labels:
    app: dotnet-app
    tags.datadoghq.com/env: "k8s-lab"
    tags.datadoghq.com/service: "dotnet-app"
    tags.datadoghq.com/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
        tags.datadoghq.com/env: "k8s-lab"
        tags.datadoghq.com/service: "dotnet-app"
        tags.datadoghq.com/version: "latest"
      annotations: {}
    spec:
      containers:
      - name: dotnet-app
        image: YOUR_DOCKERHUB_USERNAME/dotnet-app:latest
        ports:
        - containerPort: 80
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_AGENT_PORT
            value: "8126"
          - name: DD_DOGSTATSD_PORT
            value: "8125"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_SERVICE
            value: "dotnet-app"
          - name: DD_ENV
            value: "k8s-lab"
          - name: DD_VERSION
            value: "latest"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: DD_TRACE_METRICS_ENABLED
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_EXCEPTION_REPLAY_ENABLED
            value: "true"
