apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  labels:
    app: dotnet-app
    tags.datadoghq.com/env: "mentoria"
    tags.datadoghq.com/service: "dotnet-app"
    tags.datadoghq.com/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
        tags.datadoghq.com/env: "mentoria"
        tags.datadoghq.com/service: "dotnet-app"
        tags.datadoghq.com/version: "latest"
      annotations:
        ad.datadoghq.com/dotnet-app.logs: '[{"source": "dotnet", "service": "dotnet-app"}]'
    spec:
      containers:
      - name: dotnet-app
        image: araujoajoao/dotnet-app:latest
        ports:
        - containerPort: 80
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_AGENT_PORT
            value: "8126"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_SERVICE
            value: "dotnet-app"
          - name: DD_ENV
            value: "mentoria"
          - name: DD_VERSION
            value: "latest"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: DD_TRACE_METRICS_ENABLED
            value: "true"
