apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java-app
    tags.datadoghq.com/env: "develop"
    tags.datadoghq.com/service: "java-app"
    tags.datadoghq.com/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
        tags.datadoghq.com/env: "develop"
        tags.datadoghq.com/service: "java-app"
        tags.datadoghq.com/version: "latest"
      annotations:
        ad.datadoghq.com/java-app.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "prometheus_url": "http://%%host%%:8080/metrics",
                  "namespace": "java_app",
                  "metrics": ["*"]
                }
              ]
            }
          }
        ad.datadoghq.com/java-app.logs: '[{"source": "java", "service": "java-app"}]'
    spec:
      containers:
      - name: java-app
        image: araujoajoao/java-app:latest
        ports:
        - containerPort: 8080
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_AGENT_PORT
            value: "8126"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_SERVICE
            value: "java-app"
          - name: DD_ENV
            value: "develop"
          - name: DD_VERSION
            value: "latest"
