apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: apps
  labels:
    app: java-app
    tags.datadoghq.com/env: "k8s-lab"
    tags.datadoghq.com/service: "java-app"
    tags.datadoghq.com/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
        tags.datadoghq.com/env: "k8s-lab"
        tags.datadoghq.com/service: "java-app"
        tags.datadoghq.com/version: "latest"
      annotations:
        admission.datadoghq.com/java-lib.version: "latest"
    spec:
      containers:
      - name: java-app
        image: YOUR_DOCKERHUB_USERNAME/java-app:latest
        ports:
        - containerPort: 8080
        env:
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: LOGGING_CONFIG
            value: "/logging/logback.xml"
          - name: DD_SERVICE
            value: "java-app"
          - name: DD_ENV
            value: "k8s-lab"
          - name: DD_VERSION
            value: "latest"
          - name: DD_JVM_METRICS_ENABLED
            value: "true"
          - name: SPRING_MAIN_BANNER_MODE
            value: "off"
          - name: PYTHON_FLASK_URL
            value: "http://python-app:5000"
          - name: PYTHON_SERVICE_URL
            value: "http://python-app:5000"
          - name: SPRING_MVC_ASYNC_REQUEST_TIMEOUT
            value: "15000"
        volumeMounts:
        - name: java-logging-config
          mountPath: /logging
      volumes:
      - name: java-logging-config
        configMap:
          name: java-logging-config
