apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
      annotations:
        ad.datadoghq.com/python-app.logs: '[{"source": "python", "service": "python-app"}]'
    spec:
      containers:
      - name: python-app
        image: araujoajoao/python-app:latest
        ports:
        - containerPort: 8000
        env:
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_SERVICE
            value: "python-app"
          - name: DD_ENV
            value: "develop"
          - name: DD_VERSION
            value: "latest"
