apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
    tags.datadoghq.com/env: "mentoria"
    tags.datadoghq.com/service: "python-app"
    tags.datadoghq.com/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
        tags.datadoghq.com/env: "mentoria"
        tags.datadoghq.com/service: "python-app"
        tags.datadoghq.com/version: "latest"
      annotations:
        ad.datadoghq.com/python-app.logs: '[{"source": "python", "service": "python-app"}]'
    spec:
      containers:
      - name: python-app
        image: araujoajoao/python-app:latest
        ports:
        - containerPort: 5000
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_AGENT_PORT
            value: "8126"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_SERVICE
            value: "python-app"
          - name: DD_ENV
            value: "mentoria"
          - name: DD_VERSION
            value: "latest"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
