apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: apps
  labels:
    app: python-app
    tags.datadoghq.com/env: "mentoria"
    tags.datadoghq.com/service: "python-app"
    tags.datadoghq.com/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
        tags.datadoghq.com/env: "mentoria"
        tags.datadoghq.com/service: "python-app"
        tags.datadoghq.com/version: "latest"
      annotations:
        admission.datadoghq.com/python-lib.version: "latest"
    spec:
      containers:
      - name: python-app
        image: araujoajoao/python-app:py311
        command: ["python", "/startup/entrypoint.py"]
        ports:
        - containerPort: 5000
        env:
          - name: DD_AGENT_HOST
            value: "datadog-agent.default.svc.cluster.local"
          - name: DD_TRACE_AGENT_PORT
            value: "8126"
          - name: DD_DOGSTATSD_PORT
            value: "8125"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_SERVICE
            value: "python-app"
          - name: DD_ENV
            value: "mentoria"
          - name: DD_VERSION
            value: "latest"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
        volumeMounts:
        - name: python-logging-patch
          mountPath: /startup
      volumes:
      - name: python-logging-patch
        configMap:
          name: python-logging-patch
