apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
    tags.datadoghq.com/env: "k8s-lab"
    tags.datadoghq.com/service: "apache"
    tags.datadoghq.com/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        tags.datadoghq.com/env: "k8s-lab"
        tags.datadoghq.com/service: "apache"
        tags.datadoghq.com/version: "latest"
      annotations:
        ad.datadoghq.com/httpd-setup.exclude: "true"
        ad.datadoghq.com/apache.logs: '[{"source": "apache", "service": "apache"}]'
        ad.datadoghq.com/apache.checks: |
          {
            "apache": {
              "instances": [
                {
                  "apache_status_url": "http://%%host%%/server-status?auto"
                }
              ]
            }
          }
    spec:
      initContainers:
      - name: httpd-setup
        image: httpd:latest
        command:
          - sh
          - -c
          - |
            cp -r /usr/local/apache2/conf/* /conf/
            echo "<Location /server-status>" >> /conf/httpd.conf
            echo "    SetHandler server-status" >> /conf/httpd.conf
            echo "    Require all granted" >> /conf/httpd.conf
            echo "</Location>" >> /conf/httpd.conf
            echo "ExtendedStatus On" >> /conf/httpd.conf
        volumeMounts:
        - name: httpd-conf
          mountPath: /conf
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_DOGSTATSD_PORT
            value: "8125"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_SERVICE
            value: "apache"
          - name: DD_ENV
            value: "k8s-lab"
          - name: DD_VERSION
            value: "latest"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_EXCEPTION_REPLAY_ENABLED
            value: "true"
        volumeMounts:
        - name: httpd-conf
          mountPath: /usr/local/apache2/conf
        - name: apache-logs
          mountPath: /usr/local/apache2/logs
      volumes:
      - name: httpd-conf
        emptyDir: {}
      - name: apache-logs
        emptyDir: {}
