apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
    tags.datadoghq.com/env: "develop"
    tags.datadoghq.com/service: "apache"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        tags.datadoghq.com/env: "develop"
        tags.datadoghq.com/service: "apache"
      annotations:
        ad.datadoghq.com/apache.logs: '[{"source": "apache", "service": "apache"}]'
        ad.datadoghq.com/apache.checks: |
          {
            "apache": {
              "instances": [
                {
                  "apache_status_url": "http://%%host%%/server-status?auto"
                }
              ]
            }
          }
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-logs
          mountPath: /var/log/apache2
      volumes:
      - name: apache-logs
        emptyDir: {}
