apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: default
type: Opaque
data:
  api-key: MjcyNjI2ZDA5NjA2MjQyODk1YmZlOTA4NThmZDZlNw==  # base64 encoded API key
  app-key: NmFiZTZiMzk3OTg5MmZhZThjMjIzNGY1MzBlZjY0NzczNDVmZWU0Zg==  # base64 encoded App key 