apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: default
spec:
  global:
    clusterName: "appoena-lab"
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
    kubelet:
      tlsVerify: false
    tags:
      - "env:mentoria"
      - "k8s_cluster:appoena-lab"
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126
      instrumentation:
        enabled: true
    processDiscovery:
      enabled: true
    orchestratorExplorer:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    eventCollection:
      collectKubernetesEvents: true
    clusterChecks:
      enabled: true
    admissionController:
      enabled: true
      mutateUnlabelled: false
    npm:
      enabled: true
    usm:
      enabled: true
  override:
    nodeAgent:
      image:
        tag: "7.78.1"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          operator: Exists
      env:
        - name: DD_HOSTNAME
          value: "lab-mentoria"
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DD_KUBELET_TLS_VERIFY
          value: "false"
        - name: DD_COLLECT_KUBERNETES_EVENTS
          value: "true"
        - name: DD_ENABLE_ORCHESTRATOR_EXPLORER
          value: "true"
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_PROCESS_AGENT_ENABLED
          value: "true"
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "true"
        - name: DD_CONTAINER_EXCLUDE_LOGS
          value: "kube_namespace:kube-system kube_namespace:local-path-storage name:kindnetd"
        - name: DD_ENV
          value: "mentoria"
        - name: DD_DATABASE_MONITORING_ENABLED
          value: "true"
        - name: DD_IGNORE_AUTOCONF
          value: "kube_controller_manager"
    clusterAgent:
      replicas: 1
      image:
        tag: "7.78.1"
