apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
  labels:
    app: apache
  namespace: default
data:
  apache.yaml: |-
    init_config:

    instances:
      - apache_status_url: http://%%host%%/server-status?auto

    logs:
      - type: file
        path: /usr/local/apache2/logs/access_log
        source: apache
      - type: file
        path: /usr/local/apache2/logs/error_log
        source: apache
