apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    app: rabbitmq
  namespace: default
data:
  rabbitmq.yaml: |-
    logs:
      - type: file
        path: /var/log/rabbitmq/rabbit@*.log
        source: rabbitmq